# Generated by Django 5.2.8 on 2025-12-02 11:03

import django.db.models.deletion
import efactor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('tel', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره تلفن')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('fee', models.IntegerField(verbose_name='في')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('tel', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره تلفن')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default=None, max_length=100, null=True, validators=[efactor.models.valid_date], verbose_name='تاريخ فاکتور')),
                ('barcode', models.CharField(default=efactor.models.random_string, max_length=100, unique=True, verbose_name='بارکد')),
                ('customer_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='efactor.customer', verbose_name='نام خريدار')),
                ('seller_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='efactor.seller', verbose_name='نام فروشنده')),
            ],
        ),
        migrations.CreateModel(
            name='Productlst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='تعداد')),
                ('factor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efactor.factor', verbose_name='شماره فاکتور')),
                ('obj_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efactor.product', verbose_name='نام کالا')),
            ],
        ),
    ]
